import { Project, FaqItem } from './types';

export const projects: Project[] = [
  {
    title: "Bloom & Wild",
    category: "E-Commerce",
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f7a07d?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    desc: "A bespoke flower delivery platform. I used AI to generate unique product descriptions for over 50 items and optimized images for lightning-fast loading speeds on mobile.",
    tags: ["Shopify", "Midjourney Assets", "SEO"]
  },
  {
    title: "Lens & Light",
    category: "Portfolio",
    image: "https://images.unsplash.com/photo-1452587925148-ce544e77e70d?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    desc: "A high-end photography portfolio designed to showcase visuals without distraction. Includes a client proofing area.",
    tags: ["React", "Tailwind", "Gallery"]
  },
  {
    title: "TechFlow SaaS",
    category: "Landing Page",
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    desc: "Focused on conversion rate optimization (CRO). We A/B tested headlines generated by AI to find the winning combination that increased signups by 40%.",
    tags: ["Webflow", "Copywriting", "Analytics"]
  },
  {
    title: "Sarah Finance",
    category: "Service Business",
    image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    desc: "A clean, professional site for a financial consultant. Features automated Calendly booking integration and a secure client portal.",
    tags: ["Wordpress", "Booking System", "Security"]
  },
  {
    title: "The Daily Grind",
    category: "Content / Blog",
    image: "https://images.unsplash.com/photo-1499750310159-5b5f09692064?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    desc: "A lifestyle blog designed for ad revenue. Structure optimized for Core Web Vitals to ensure high search engine ranking.",
    tags: ["Ghost CMS", "AdSense", "Newsletter"]
  },
  {
    title: "FitTrack App",
    category: "Web Application",
    image: "https://images.unsplash.com/photo-1555421689-d68471e189f2?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    desc: "Marketing site for a new fitness app. Features complex CSS animations and 3D device mockups created with AI tools.",
    tags: ["Three.js", "Animation", "App Store"]
  }
];

export const faqs: FaqItem[] = [
  {
    question: "How does \"AI-Powered\" help me?",
    answer: "It means I use advanced tools to generate clean code, write SEO-friendly copy, and optimize images faster than traditional methods. This saves you money and gets your site live weeks sooner."
  },
  {
    question: "Do I own the website after it's done?",
    answer: "Absolutely. 100%. Once the final payment is made, I transfer all files, domains, and admin access to you. You are the sole owner."
  },
  {
    question: "What platform do you use?",
    answer: "It depends on your needs. For e-commerce, I usually suggest Shopify or Woocommerce. For business sites, I often use WordPress or custom code (React/Tailwind) for maximum speed."
  }
];