-- Run this in your Supabase SQL Editor to setup the database

-- 1. Create the table for contact form submissions if it doesn't exist
create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  email text,
  service text,
  message text
);

-- 2. Enable Row Level Security (RLS) for contact_messages
alter table public.contact_messages enable row level security;

-- 3. Create the policy to allow public inserts
drop policy if exists "Enable insert for everyone" on public.contact_messages;
create policy "Enable insert for everyone" 
on public.contact_messages 
for insert 
with check (true);

-- =========================================================
-- NEW: USER PROFILES SETUP
-- =========================================================

-- 4. Create a profiles table to hold user information
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  full_name text,
  company_name text,
  website text,
  phone text,
  avatar_url text
);

-- 5. Enable RLS on profiles
alter table public.profiles enable row level security;

-- 6. Create policies for profiles
drop policy if exists "Public profiles are viewable by everyone." on profiles;
create policy "Public profiles are viewable by everyone." 
  on profiles for select using ( true );

drop policy if exists "Users can insert their own profile." on profiles;
create policy "Users can insert their own profile." 
  on profiles for insert with check ( auth.uid() = id );

drop policy if exists "Users can update own profile." on profiles;
create policy "Users can update own profile." 
  on profiles for update using ( auth.uid() = id );

-- 7. Create a trigger to automatically create a profile entry when a user signs up via Supabase Auth
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (
    new.id, 
    new.raw_user_meta_data->>'full_name', 
    new.raw_user_meta_data->>'avatar_url'
  );
  return new;
end;
$$ language plpgsql security definer;

-- Trigger the function every time a user is created
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
