import React, { useState } from 'react';
import { Mail, MessageCircle, Calendar, CheckCircle, AlertCircle, Loader2, Database, Copy } from 'lucide-react';
import { supabase } from '../supabaseClient';

const Contact: React.FC = () => {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    service: 'Landing Page',
    message: ''
  });
  const [status, setStatus] = useState<'idle' | 'loading' | 'success' | 'error'>('idle');
  const [errorMessage, setErrorMessage] = useState('');
  const [sqlFix, setSqlFix] = useState<string | null>(null);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    setFormData(prev => ({
      ...prev,
      [e.target.id]: e.target.value
    }));
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    alert('SQL copied to clipboard!');
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setStatus('loading');
    setErrorMessage('');
    setSqlFix(null);

    try {
      // Sending data to 'contact_messages' table
      // We do NOT use .select() here because that requires a SELECT policy (Read access),
      // which we don't want to grant to the public for privacy reasons.
      const { error } = await supabase
        .from('contact_messages')
        .insert([
          { 
            name: formData.name, 
            email: formData.email, 
            service: formData.service, 
            message: formData.message,
            created_at: new Date().toISOString()
          }
        ]);

      if (error) {
        throw error;
      }

      setStatus('success');
      setFormData({ name: '', email: '', service: 'Landing Page', message: '' });
      
    } catch (err: any) {
      console.error('Error submitting form details:', JSON.stringify(err, null, 2));
      
      let msg = 'Failed to send message.';
      
      // Check for specific Supabase error codes
      if (err?.code === 'PGRST205') {
        msg = 'Database Error: Table "contact_messages" not found.';
        const sql = `create table contact_messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  email text,
  service text,
  message text
);
alter table contact_messages enable row level security;
create policy "Enable insert for everyone" on contact_messages for insert with check (true);`;
        setSqlFix(sql);
      } else if (err?.code === '42501') {
        msg = 'Permission Error: RLS Policy Violation.';
        // This SQL fixes the specific 42501 error by ensuring the INSERT policy exists
        const sql = `drop policy if exists "Enable insert for everyone" on contact_messages;

create policy "Enable insert for everyone" 
on contact_messages 
for insert 
with check (true);`;
        setSqlFix(sql);
      }
      else {
        // Heuristic to detect common config errors
        const errString = JSON.stringify(err).toLowerCase();
        if (errString.includes('apikey') || errString.includes('auth') || errString.includes('401')) {
           msg = 'Authentication Error: Please check your Supabase API Key (anon public key) in supabaseClient.ts.';
        } else if (errString.includes('policy') || errString.includes('permission')) {
           msg = 'Permission Error: Please check Row Level Security (RLS) policies on your Supabase table.';
        } else if (typeof err === 'string') {
          msg = err;
        } else if (err && typeof err === 'object') {
          if (err.message) {
            msg = err.message;
          } else if (err.error_description) {
            msg = err.error_description;
          } else if (err.details) {
            msg = err.details;
          }
        }
      }

      setStatus('error');
      setErrorMessage(msg);
    }
  };

  return (
    <section id="contact" className="py-20 bg-slate-950">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-16">
          {/* Contact Info */}
          <div>
            <h2 className="text-base text-primary-400 font-semibold tracking-wide uppercase">Get In Touch</h2>
            <h3 className="mt-2 text-3xl font-bold text-white font-display">Ready to Build a Website That Actually Converts?</h3>
            <p className="mt-4 text-lg text-slate-400">
              Don't let another customer slip away. Book your free strategy call today and let's discuss how we can grow your business.
            </p>

            <div className="mt-8 space-y-6">
              <div className="flex items-center gap-4">
                <div className="w-12 h-12 bg-primary-50 rounded-lg flex items-center justify-center text-primary-600">
                  <Mail className="w-6 h-6" />
                </div>
                <div>
                  <p className="text-sm font-medium text-gray-900 text-white">Email Me</p>
                  <a href="mailto:hello@alexdev.com" className="text-gray-500 text-slate-400 hover:text-primary-600 transition-colors">hello@alexdev.com</a>
                </div>
              </div>
              <div className="flex items-center gap-4">
                <div className="w-12 h-12 bg-green-50 rounded-lg flex items-center justify-center text-green-600">
                  <MessageCircle className="w-6 h-6" />
                </div>
                <div>
                  <p className="text-sm font-medium text-gray-900 text-white">WhatsApp</p>
                  <a href="#" className="text-gray-500 text-slate-400 hover:text-green-600 transition-colors">+1 (555) 123-4567</a>
                </div>
              </div>
              <div className="flex items-center gap-4">
                <div className="w-12 h-12 bg-purple-50 rounded-lg flex items-center justify-center text-purple-600">
                  <Calendar className="w-6 h-6" />
                </div>
                <div>
                  <p className="text-sm font-medium text-gray-900 text-white">Book a Call</p>
                  <a href="#" className="text-gray-500 text-slate-400 hover:text-purple-600 transition-colors">View Calendly Availability</a>
                </div>
              </div>
            </div>
          </div>

          {/* Contact Form */}
          <div className="bg-gray-50 rounded-2xl p-8 shadow-sm relative overflow-hidden min-h-[480px]">
            {status === 'success' ? (
              <div className="absolute inset-0 bg-white flex flex-col items-center justify-center p-8 text-center animate-in fade-in duration-300">
                <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mb-4">
                  <CheckCircle className="w-8 h-8 text-green-600" />
                </div>
                <h3 className="text-2xl font-bold text-gray-900 mb-2">Message Sent!</h3>
                <p className="text-gray-600">Thanks for reaching out. I've received your details and will be in touch shortly.</p>
                <button 
                  onClick={() => setStatus('idle')}
                  className="mt-6 px-6 py-2 bg-gray-100 text-gray-700 font-medium rounded-full hover:bg-gray-200 transition-colors"
                >
                  Send another message
                </button>
              </div>
            ) : (
              <form onSubmit={handleSubmit} className="space-y-6">
                <div>
                  <label htmlFor="name" className="block text-sm font-medium text-gray-700">Name</label>
                  <input 
                    type="text" 
                    id="name" 
                    required 
                    value={formData.name}
                    onChange={handleChange}
                    className="mt-1 block w-full px-4 py-3 rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm bg-white border outline-none transition-colors" 
                    placeholder="Your Name" 
                  />
                </div>

                <div>
                  <label htmlFor="email" className="block text-sm font-medium text-gray-700">Email</label>
                  <input 
                    type="email" 
                    id="email" 
                    required 
                    value={formData.email}
                    onChange={handleChange}
                    className="mt-1 block w-full px-4 py-3 rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm bg-white border outline-none transition-colors" 
                    placeholder="you@company.com" 
                  />
                </div>

                <div>
                  <label htmlFor="service" className="block text-sm font-medium text-gray-700">Interested In</label>
                  <select 
                    id="service" 
                    value={formData.service}
                    onChange={handleChange}
                    className="mt-1 block w-full px-4 py-3 rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm bg-white border outline-none transition-colors"
                  >
                    <option>Landing Page</option>
                    <option>Full Website</option>
                    <option>E-Commerce</option>
                    <option>Other</option>
                  </select>
                </div>

                <div>
                  <label htmlFor="message" className="block text-sm font-medium text-gray-700">Message</label>
                  <textarea 
                    id="message" 
                    rows={4} 
                    required 
                    value={formData.message}
                    onChange={handleChange}
                    className="mt-1 block w-full px-4 py-3 rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm bg-white border outline-none transition-colors" 
                    placeholder="Tell me a bit about your project..."
                  ></textarea>
                </div>

                {status === 'error' && (
                  <div className="flex flex-col gap-2 text-red-600 text-sm bg-red-50 p-4 rounded-md border border-red-100">
                    <div className="flex items-center gap-2">
                      <AlertCircle className="w-5 h-5 flex-shrink-0" />
                      <span className="leading-relaxed font-semibold">{errorMessage}</span>
                    </div>
                    {sqlFix && (
                      <div className="mt-2 text-slate-700">
                        <p className="mb-2 text-xs uppercase font-bold tracking-wide text-slate-500 flex items-center gap-2">
                          <Database className="w-3 h-3" /> Solution: Run this in Supabase SQL Editor
                        </p>
                        <div className="relative group">
                          <pre className="bg-slate-900 text-slate-300 p-3 rounded text-xs overflow-x-auto whitespace-pre-wrap font-mono border border-slate-700">
                            {sqlFix}
                          </pre>
                          <button 
                            type="button"
                            onClick={() => copyToClipboard(sqlFix)}
                            className="absolute top-2 right-2 p-1 bg-slate-700 hover:bg-slate-600 text-white rounded opacity-0 group-hover:opacity-100 transition-opacity"
                            title="Copy SQL"
                          >
                            <Copy className="w-3 h-3" />
                          </button>
                        </div>
                      </div>
                    )}
                  </div>
                )}

                <button 
                  type="submit" 
                  disabled={status === 'loading'}
                  className="w-full flex justify-center py-3 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-gray-900 hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-900 transition-colors disabled:opacity-70 disabled:cursor-not-allowed"
                >
                  {status === 'loading' ? (
                    <span className="flex items-center gap-2">
                      <Loader2 className="w-4 h-4 animate-spin" /> Sending...
                    </span>
                  ) : (
                    "Send Message"
                  )}
                </button>
              </form>
            )}
          </div>
        </div>
      </div>
    </section>
  );
};

export default Contact;